name: Test

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
